<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>meat</string>
	</array>
	<key>foldingStartMarker</key>
	<string>\{$</string>
	<key>foldingStopMarker</key>
	<string>^\t*\}</string>
	<key>name</key>
	<string>meat</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function</string>
				</dict>
			</dict>
			<key>match</key>
			<string> ([a-zA-Z]+:) </string>
			<key>name</key>
			<string>meta.selector.keyword</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function</string>
				</dict>
			</dict>
			<key>match</key>
			<string> ([+\-*/=&lt;&gt;:\.]+) </string>
			<key>name</key>
			<string>meta.selector.binary</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function</string>
				</dict>
			</dict>
			<key>match</key>
			<string> ([a-zA-Z]+)</string>
			<key>name</key>
			<string>meta.selector.unary</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"$</string>
			<key>end</key>
			<string>"$</string>
			<key>name</key>
			<string>comment</string>
		</dict>
		<dict>
			<key>match</key>
			<string>'.*'</string>
			<key>name</key>
			<string>string</string>
		</dict>
		<dict>
			<key>match</key>
			<string>[a-zA-Z]+</string>
			<key>name</key>
			<string>variable</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.meat</string>
	<key>uuid</key>
	<string>2260CF36-730E-4530-BC35-495BD3D890D9</string>
</dict>
</plist>
